# Generated by Django 6.0.3 on 2026-03-24 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Transaction')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('sender_id', models.CharField(max_length=50, verbose_name='ID Expéditeur')),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone Expéditeur')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='Nom Expéditeur')),
                ('receiver_id', models.CharField(max_length=50, verbose_name='ID Destinataire')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone Destinataire')),
                ('receiver_name', models.CharField(blank=True, max_length=100, verbose_name='Nom Destinataire')),
                ('transaction_type', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('VIREMENT', 'Virement Bancaire'), ('RETRAIT_GAB', 'Retrait GAB'), ('ACHAT_LIGNE', 'Achat en Ligne'), ('PAIEMENT_POS', 'Paiement POS'), ('DEPOT', 'Dépôt Espèces')], max_length=20, verbose_name='Type')),
                ('merchant_category', models.CharField(choices=[('ALIMENTATION', 'Alimentation & Épicerie'), ('TELECOM', 'Télécommunications'), ('TRANSPORT', 'Transport'), ('SANTE', 'Santé & Pharmacie'), ('EDUCATION', 'Éducation'), ('IMMOBILIER', 'Immobilier'), ('ELECTRONIQUE', 'Électronique'), ('RESTAURANT', 'Restaurant & Hôtellerie'), ('CARBURANT', 'Station Service'), ('TRANSFERT', "Transfert d'Argent"), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie Marchand')),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile (Application)'), ('WEB', 'Navigateur Web'), ('POS', 'Terminal POS'), ('ATM', 'Guichet Automatique'), ('USSD', 'USSD (*XXX#)')], max_length=10, verbose_name='Appareil')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country_code', models.CharField(default='SN', max_length=5, verbose_name='Code Pays')),
                ('hour_of_day', models.IntegerField(verbose_name='Heure de la journée')),
                ('day_of_week', models.IntegerField(verbose_name='Jour de la semaine (0=Lundi)')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Week-end')),
                ('is_night', models.BooleanField(default=False, verbose_name='Transaction nocturne')),
                ('distance_from_home', models.FloatField(default=0.0, verbose_name='Distance domicile (km)')),
                ('is_foreign_ip', models.BooleanField(default=False, verbose_name='IP Étrangère')),
                ('is_new_device', models.BooleanField(default=False, verbose_name='Nouvel Appareil')),
                ('failed_attempts_24h', models.IntegerField(default=0, verbose_name='Tentatives échouées 24h')),
                ('freq_transactions_24h', models.IntegerField(default=1, verbose_name='Nb transactions 24h')),
                ('freq_transactions_7d', models.IntegerField(default=1, verbose_name='Nb transactions 7j')),
                ('avg_amount_30d', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant moyen 30j')),
                ('max_amount_30d', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant max 30j')),
                ('ratio_to_avg', models.FloatField(default=1.0, verbose_name='Ratio montant / moyenne')),
                ('nb_unique_receivers_7d', models.IntegerField(default=1, verbose_name='Destinataires uniques 7j')),
                ('is_first_transaction', models.BooleanField(default=False, verbose_name='Première transaction')),
                ('status', models.CharField(choices=[('EN_ATTENTE', "En attente d'analyse"), ('LEGITIME', 'Transaction légitime'), ('SUSPECTE', 'Suspecte — sous surveillance'), ('FRAUDULEUSE', 'Fraude confirmée'), ('BLOQUEE', 'Bloquée automatiquement')], db_index=True, default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('is_fraud', models.BooleanField(blank=True, null=True, verbose_name='Est une fraude (ground truth)')),
                ('fraud_score', models.FloatField(blank=True, null=True, verbose_name='Score de fraude (0-1)')),
                ('fraud_label', models.CharField(blank=True, max_length=20, verbose_name='Label fraude prédit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_simulated', models.BooleanField(default=False, verbose_name='Donnée simulée')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='transaction_timesta_20dac7_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['sender_id'], name='transaction_sender__ccd105_idx'), models.Index(fields=['is_fraud'], name='transaction_is_frau_237d47_idx'), models.Index(fields=['fraud_score'], name='transaction_fraud_s_d1c1e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Modèle ML')),
                ('model_version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('prediction', models.IntegerField(verbose_name='Prédiction (0=normal, 1=fraude, -1=anomalie)')),
                ('confidence_score', models.FloatField(verbose_name='Score de confiance')),
                ('inference_time_ms', models.FloatField(verbose_name="Temps d'inférence (ms)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Prédiction ML',
                'verbose_name_plural': 'Prédictions ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITIQUE', 'Critique (≥85%)'), ('ELEVE', 'Élevé (≥65%)'), ('MOYEN', 'Moyen (≥50%)')], max_length=10, verbose_name='Niveau')),
                ('fraud_score', models.FloatField(verbose_name='Score de fraude')),
                ('message', models.TextField(verbose_name="Message d'alerte")),
                ('status', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('FAUX_POSITIF', 'Faux positif')], default='NOUVELLE', max_length=15, verbose_name='Statut')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Note de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='transactions.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
